<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="wwwroot\imagenes\" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="IPC2_Proyecto2.Tests\**\*.cs" />
    <Content Remove="IPC2_Proyecto2.Tests\**\*" />
    <EmbeddedResource Remove="IPC2_Proyecto2.Tests\**\*" />
    <None Remove="IPC2_Proyecto2.Tests\**\*" />
  </ItemGroup>

</Project>
